@local = http://localhost:3000


### 
GET {{local}}/v1/public/usuarios/José
Content-Type: application/json

{ }

### 
POST {{local}}/v1/public/usuarios
Content-Type: application/json

{
"nome": "José",
"id": "01",
"login": "José",
"email": "w@gmail.com",
"senha": "123456",
"joinDate": "06/08/2021"
}